import argparse
import json
from dataclasses import asdict
from pathlib import Path

from tqdm import tqdm

from data_processing import get_dataset_splits, load_dataset_split
from evaluation_pipeline import (
    aggregate_results,
    evaluate_generated_mindmap,
)
from generation_pipeline import LocalLLMMindMapGenerator
from few_shot import build_few_shot_examples


def save_json(path: str | Path, rows: list[dict]) -> None:
    """Save rows to a pretty-printed JSON file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as file:
        json.dump(
            rows,
            file,
            ensure_ascii=False,
            indent=2,
        )
        file.write("\n")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--data-dir",
        type=str,
        default="data",
        help="Dataset root directory.",
    )

    parser.add_argument(
        "--split",
        type=str,
        choices=["dev", "test"],
        default="dev",
        help="Dataset split to evaluate.",
    )

    parser.add_argument(
        "--model",
        type=str,
        default="Qwen/Qwen2.5-3B-Instruct",
        help="Local HuggingFace model name or path.",
    )

    parser.add_argument(
        "--quantization",
        type=str,
        choices=["none", "4bit", "8bit"],
        default="none",
        help="Model quantization mode. Use 4bit or 8bit to reduce GPU memory usage.",
    )

    parser.add_argument(
        "--few-shot-count",
        type=int,
        choices=[0, 1, 2, 3],
        default=0,
        help="Number of few-shot examples from the dev set.",
    )

    parser.add_argument(
        "--max-nodes",
        type=int,
        default=None,
        help="Optional hard limit for selected mind-map nodes. Default: no limit.",
    )

    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=2048,
        help="Maximum number of new tokens generated by the model.",
    )

    parser.add_argument(
        "--temperature",
        type=float,
        default=0.0,
        help="Generation temperature.",
    )

    parser.add_argument(
        "--max-files",
        type=int,
        default=None,
        help="Optional limit for debugging.",
    )

    parser.add_argument(
        "--output-json",
        type=str,
        default="outputs/generated_mindmaps.json",
        help="Path for detailed generation/evaluation outputs.",
    )

    return parser.parse_args()


def main() -> None:
    """Generate and evaluate LLM mind maps on a predefined split."""
    args = parse_args()

    splits = get_dataset_splits(args.data_dir)

    dev_items = load_dataset_split(splits["dev"])
    split = splits[args.split]
    items = load_dataset_split(split)

    few_shot_examples = build_few_shot_examples(
        dev_items=dev_items,
        count=args.few_shot_count,
    )

    few_shot_article_ids = {example.article_id for example in few_shot_examples}

    if args.split == "dev" and few_shot_article_ids:
        items = [
            item
            for item in items
            if item.article_id not in few_shot_article_ids
        ]

    if args.max_files is not None:
        items = items[: args.max_files]

    generator = LocalLLMMindMapGenerator(
        model_name=args.model,
        max_nodes=args.max_nodes,
        temperature=args.temperature,
        max_new_tokens=args.max_new_tokens,
        few_shot_examples=few_shot_examples,
        quantization=args.quantization,
    )

    output_rows = []
    evaluation_results = []

    for item in tqdm(items, desc=f"Generating {args.split} mind maps"):
        try:
            generated = generator.generate(item.sentences)

            evaluation = evaluate_generated_mindmap(
                article_id=item.article_id,
                generated_pairs=generated["pairs"],
                reference_path=item.reference_path,
            )

            evaluation_results.append(evaluation)

            generation_for_output = {
                key: value
                for key, value in generated.items()
                if key != "pairs"
            }

            output_rows.append(
                {
                    "article_id": item.article_id,
                    "original_path": str(item.original_path),
                    "reference_path": str(item.reference_path),
                    "few_shot": {
                        "count": len(few_shot_examples),
                        "article_ids": sorted(few_shot_article_ids),
                    },
                    "sentences": item.sentences,
                    "generation": generation_for_output,
                    "evaluation": asdict(evaluation),
                }
            )

            # print(generation_for_output['rendered'])

        except Exception as exc:
            output_rows.append(
                {
                    "article_id": item.article_id,
                    "original_path": str(item.original_path),
                    "reference_path": str(item.reference_path),
                    "error": repr(exc),
                }
            )

    save_json(args.output_json, output_rows)

    aggregate = aggregate_results(evaluation_results)

    print(f"\nModel: {args.model}")
    print(f"Quantization: {args.quantization}")
    print(f"\nSplit: {args.split}")
    print(f"Evaluated articles: {len(evaluation_results)}")
    print(f"\nFew-shot count: {len(few_shot_examples)}")
    print(f"Few-shot article IDs: {sorted(few_shot_article_ids)}")
    print(f"ROUGE-1:    {aggregate['rouge_1']:.6f}")
    print(f"ROUGE-2:    {aggregate['rouge_2']:.6f}")
    print(f"ROUGE-L:    {aggregate['rouge_l']:.6f}")
    print(f"ROUGE-mean: {aggregate['rouge_mean']:.6f}")


if __name__ == "__main__":
    main()